repos:
  - repo: local
    hooks:
      - id: freeze-requirements
        name: Freeze requirements.txt
        entry: python -m pip freeze > requirements.txt
        language: system
        pass_filenames: false
